"""add field confirmed

Revision ID: 240d0bb4e548
Revises: 232dd5b91d0f
Create Date: 2023-07-14 17:45:42.270075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240d0bb4e548'
down_revision = '232dd5b91d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
